name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'iamstevedavis'
          destination-repository-name: 'iamstevedavis.github.io'
          user-email: steve@visda.ca
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
          
